export const languageInstructions = {
    'en': 'Please respond in English',
    'es': 'Por favor responde en español',
    'fr': 'Veuillez répondre en français',
    'de': 'Bitte antworten Sie auf Deutsch',
    'it': 'Per favore rispondi in italiano',
    'ja': '日本語で返信してください',
    'ko': '한국어로 답변해 주세요',
    'zh': '请用中文回答',
    'ru': 'Пожалуйста, ответьте на русском языке',
    'ar': 'الرجاء الرد باللغة العربية',
    'hi': 'कृपया हिंदी में जवाब दें',
    'pt': 'Por favor, responda em português',
    'nl': 'Gelieve in het Nederlands te antwoorden',
    'tr': 'Lütfen Türkçe cevap verin',
    'pl': 'Proszę odpowiedzieć po polsku',
    'uk': 'Будь ласка, відповідайте українською мовою',
    'vi': 'Vui lòng trả lời bằng tiếng Việt',
    'th': 'กรุณาตอบเป็นภาษาไทย',
    'da': 'Venligst svar på dansk',
    'fi': 'Vastaa suomeksi',
    'no': 'Vennligst svar på norsk',
    'sv': 'Vänligen svara på svenska'
}; 